### ISSUE TITLE
I just want to tell you about a command which turns UUIDs into /dev notations

### ISSUE THREAD

**Issue by 32th-System** [cleverwise/pdisks#1]
This command does this: 
`lsblk -o UUID,NAME | grep $UUID | awk '{print $2}' | cut -c 7-`
Explanation:
`lsblk -o UUID,NAME` will run `lsblk` with parameters telling it to print the UUID and the device name.
`grep $UUID` will grab the line containing the UUID of the partition.
`awk '{print $2}'` will grab the string of text after the space.
`cut -c 7-` will cut off the first 7 characters, which are used to display the `lsblk` output as a tree. It may not seem like there are 7 characters before the name of the `/dev` notation, but they are in fact 7 characters.

I hope I could help you to improve the script, so that it may also be able to use UUIDs in order to identify the partition(s) which should be protected.

**Comment by cleverwise** [comment]
Thank you for the post.

I did think about UUIDs.  I would need to consider the best way to mix it into pdisks.  Obviously UUIDs only wouldn't work as that doesn't protect say overwriting /dev/sda, since there is no UUID.

We shall see what develops.

Thanks again for the thoughts.

**Comment by 32th-System** [comment]
What you could do is use UUIDs in order to find out which partitions are supposed to be protected and use the `/dev` notation in order to identify the drive to be protected if the configuration file specifies to protect the drive itself as well. You would grab the `sda` out of the `sda1` in order to identify the drive itself. So it is very possible to use UUIDs in order to identify physical storage devices as well.
PS: A utility  with the exact same name but a different purpose exists.

**Comment by 32th-System** [comment]
I found a command which is much better than what I came up with. The command is:
```
realpath /dev/disk/by-uuid/$UUID
```
It is much simpler and outputs the full `/dev` path. Doesn't require root as well.

**Comment by cleverwise** [comment]
Thanks for passing along that command.  It is interesting.

This was just a fun little project that I didn't want to spend a lot time on (so many other items on my plate).  I did think about UUIDs but it was just much quicker to do ls /dev/sd* which only requires grabbing the results.

However I am not opposed or anything to making the script better, when I can find the time.  :-)
